use_frameworks!

platform :ios, '8.0'

target 'HCDebugTool_Example' do
  pod 'HCDebugTool', :path => '../'
  pod 'FlexBoxLayout' # https://github.com/carlSQ/FlexBoxLayout
  pod 'GYHttpMock'
  pod 'AFNetworking'
#  pod 'YogaKit'
#  pod 'HCDebugTool'

  target 'HCDebugTool_Tests' do
    inherit! :search_paths

    
  end
end
